config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :follows
  resources :articles
  devise_for :users, path: 'auth', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      registration: 'register',
      sign_up: 'cmon_let_me_in'
  }

  root to: 'articles#index'

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user

  has_many :comments

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :article
  belongs_to :user

  has_many :comments

end

app/models/follow.rb
class Follow < ApplicationRecord

  belongs_to :user
  belongs_to :following, class_name: 'User'

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  has_many :articles
  has_many :comments
  has_many :follows, class_name: 'Follow', foreign_key: :user_id
  has_many :followings, class_name: 'Follow', foreign_key: :following_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  protect_from_forgery except: :create

  # GET /articles
  def index
    @articles = Article.all

  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      # params.fetch(:article, {})
      params.require(:article).permit(
          :title,
          :content
      )
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    if params[:article_id]
      @article = Article.find(params[:article_id])
      @comment = @article.comments.new(comment_params)
    end
    @comment.user = current_user
    if @comment.save!
      redirect_to article_path(@article)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :comment_id)
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_follow, only: [:show, :edit, :update, :destroy]

  # GET /follows
  def index
    @follows = Follow.where(user_id: current_user.id)
  end

  # GET /follows/1
  def show
  end

  # GET /follows/new
  def new
    @follow = Follow.new
  end

  # GET /follows/1/edit
  def edit
  end

  # POST /follows
  def create
    p 'follow_params'
    p follow_params
    p 'follow_params'
    @follow = Follow.new(follow_params)
    @follow.user = current_user
    puts @follow.valid?
    puts @follow.errors.full_messages
    
    if @follow.save
      redirect_to @follow, notice: 'follow was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /follows/1
  def update
    if @follow.update(follow_params)
      redirect_to @follow, notice: 'Follow was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /follows/1
  def destroy
    @follow.destroy
    redirect_to follows_url, notice: 'Follow was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follow
      @follow = Follow.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def follow_params
      params.require(:follow).permit(
          :following_id
      )
    end
end

app/controllers/logged_user_controller.rb
class LoggedUserController < ApplicationController

  before_action :authenticate_user!

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content, as: :text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3">Content</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td colspan="3"><%= article.content %></td>
      </tr>
      <tr style="border-bottom: 1px solid black;padding-bottom: 10px;">
        <td></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.content %>
</p>


<% if @article.user == current_user %>
  <%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>

<section>
  <%= render partial: "comments/comment", collection: @article.comments %>
</section>

<h2>Add a comment:</h2>
<% if user_signed_in? %>
  <%= simple_form_for [ @article, @article.comments.build ], remote: true do |f| %>
    <p>
      <%= f.input :content, as: :text, label: 'Comment' %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
<% else %>
  <p>
    You need to <%= link_to('Sign in', new_user_session_path) %> to leave a comment
  </p>
<% end %>

app/views/comments/_comment.erb
<p>
  <%= comment.content %>
</p>
<hr/>
<section>
  <%= render partial: 'comments/comment', collection: comment.comments %>
</section>
<hr/>
<% if user_signed_in? %>
  <%= simple_form_for [ comment.article, comment.comments.build(comment_id: comment.id) ], remote: true do |f| %>
    <%= f.hidden_field :comment_id %>
    <p>
      <%= f.input :content, as: :text, label: 'Comment' %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
<% end %>
<hr/>

app/views/followers/_form.html.erb
<%= simple_form_for(@follower) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/follows/_form.html.erb
<%= simple_form_for(@follow) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing Follow</h1>

<%= render 'form', follow: @follow %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Follows</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @follows.each do |follow| %>
      <tr>
        <td><%= link_to 'Show', follow %></td>
        <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
        <td><%= link_to 'Destroy', follow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follow', new_follow_path %>

app/views/follows/new.html.erb
<h1>New Follow</h1>

<%= render 'form', follow: @follow %>

<%= link_to 'Back', follows_path %>

app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td colspan="3"><%= user.first_name %>&nbsp;<%= user.last_name %></td>
      </tr>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
  <p>
    <%= link_to 'Follow', follows_path({ follow: { following_id: @user.id }}), method: 'post'  %>
  </p>
<% else %>
  <p>
    You need to <%= link_to('Sign in', new_user_session_path) %> to follow this user
  </p>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>